name: build-docker-images

on:
  push:
    branches: [ master ]

jobs:
  build-arno:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Run Clean Install
        run: npm ci
      - name: Build
        run: npm run build && npm prune --production
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build Inventory Image'
        run: |
          docker build -t ghcr.io/marnes/arno:latest ./
          docker push ghcr.io/marnes/arno:latest